# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ClaCgZwuuSCIO1qIm4-BWipqe1wIL2d
"""

def find_largest_number(arr):
    if not arr:
        print("المصفوفة فارغة")
        return None

    # افتراض أن أول عنصر هو الأكبر
    max_num = arr[0]

    # المرور على باقي العناصر للمقارنة
    for num in arr:
        if num > max_num:
            max_num = num

    print(f"أكبر قيمة عددية في المصفوفة هي: {max_num}")
    return max_num

# مصفوفة تجريبية لاختبار الدالة
numbers = [5, 12, 8, 44, 21, 3]
find_largest_number(numbers)