# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yb7WYYvQ5I_IjR7xdrCAYhALkwNov-OG
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set the seaborn style
sns.set_theme(style="whitegrid")

# This defines the step size h for the numerical computation.
h = 0.1

# This creates a grid x from 0 to 2*pi with intervals of h.
x = np.arange(0, 2 * np.pi, h)

# This computes the cosine function values for each point in the grid x.
y = np.cos(x)

# This calculates the forward differences of y vector divided by h
forward_diff = np.diff(y) / h

# This defines a new grid x_diff that corresponds to the forward differences.
x_diff = x[:-1]

# This calculates the exact solution for the derivative of cos(x)
exact_solution = -np.sin(x_diff)

# This code block creates a plot showing both the approximation and the exact solution
plt.figure(figsize=(12, 8))
plt.plot(x_diff, forward_diff, label='Finite difference approximation')
plt.plot(x_diff, exact_solution, label='Exact solution')
plt.legend()
plt.show()

# Finally, this computes the maximum error between the numerical derivative and the exact solution
max_error = max(abs(exact_solution - forward_diff))
print("Maximum Error is:")
print(max_error)

import numpy as np

# Function and point of interest
x0 = 0.7

# Step sizes
h = 2.0 ** -np.arange(1, 30)

# Finite difference approximation of the derivative
df = (np.cos(x0 + h) - np.cos(x0)) / h

# True value of the derivative
true_value = -np.sin(x0)

# Display the results with formatted output
print("k   | Approximation       | Ratio of errors   | Relative differences")
print("---------------------------------------------------------------------")

previous_approximation = None
previous_error = None

for k in range(1, len(h) + 1):
    approximation = df[k - 1]
    error = np.abs(approximation - true_value)

    # Calculate ratio of errors
    if previous_error is not None and error != 0:
        ratio = previous_error / error
    else:
        ratio = ""

    # Calculate relative difference
    if previous_approximation is not None:
        relative_difference = np.abs((approximation - previous_approximation) / previous_approximation)
    else:
        relative_difference = ""

    # Format the output values
    formatted_approximation = f"{approximation:.15f}"
    formatted_ratio = f"{ratio:.6f}" if isinstance(ratio, float) else ratio
    formatted_relative_difference = f"{relative_difference:.10f}" if isinstance(relative_difference, float) else relative_difference

    print(f"{k:<3} | {formatted_approximation:<19} | {formatted_ratio:<17} | {formatted_relative_difference:<20}")

    previous_error = error
    previous_approximation = approximation

# Print the true value of the derivative for reference
print(f"\nTrue value of the derivative: {true_value:.17f}")